#  _    __                              _          ____ ___
# | |_ / _|      _ __         __ _  ___(_)        / ___|_ _|
# | __| |_ _____| '_ \ _____ / _` |/ __| |       | |    | |
# | |_|  _|_____| |_) |_____| (_| | (__| |_ _ _  | |___ | |
#  \__|_|       | .__/       \__, |\___|_(_|_|_)  \____|___|
#               |_|          |___/
#
# Build; create a release if we're on a tag.
#
# ...somewhat primitive, but works for now :)

stages:
  - build
  - publish

build:
  stage: build
  image: golang:1.17
  script:
    - make local
  artifacts:
    paths:
      - terraform-provider-gitlabci

publish:
  stage: publish
  image:
    name: docker.io/goreleaser/goreleaser
    entrypoint: ['']
  variables:
    GITLAB_TOKEN: $CI_JOB_TOKEN
    GIT_DEPTH: 0
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v.*/'
  script:
    - goreleaser release --rm-dist
