#  _    __                              _          ____ ___
# | |_ / _|      _ __         __ _  ___(_)        / ___|_ _|
# | __| |_ _____| '_ \ _____ / _` |/ __| |       | |    | |
# | |_|  _|_____| |_) |_____| (_| | (__| |_ _ _  | |___ | |
#  \__|_|       | .__/       \__, |\___|_(_|_|_)  \____|___|
#               |_|          |___/
#
# Build; create a release if we're on a tag.
#
# ...somewhat primitive, but works for now :)

stages:
  - build
  - publish

build:
  stage: build
  image: golang:1.17
  script:
    - make local
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v.*/'
      when: never
    - when: always
  artifacts:
    paths:
      - terraform-provider-gitlabci

publish:
  stage: publish
  image:
    name: docker.io/goreleaser/goreleaser
    entrypoint: ['']
  variables:
    GITLAB_TOKEN: $CI_JOB_TOKEN
    GIT_DEPTH: 0
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v.*/'
  before_script:
    - apk update && apk add gnupg
    - gpg-agent --daemon --default-cache-ttl 7200
    - cat $GPG_SIGNING_KEY | gpg --import --batch --no-tty
    - echo "frobnips!" > /tmp/foo
    - gpg --detach-sig --yes -v --output=/dev/null --pinentry-mode loopback --passphrase "$(cat $GPG_PASSWORD)" /tmp/foo
  script:
    - goreleaser release --rm-dist
